Week_15/12-01-2023/ShoppingApp/ShoppingApp.Web/Controllers/CardController.cs
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShoppingApp.Business.Abstract;
using ShoppingApp.Core;
using ShoppingApp.Entity.Concrete;
using ShoppingApp.Entity.Concrete.Identity;
using ShoppingApp.Web.Models.Dtos;

namespace ShoppingApp.Web.Controllers
{
    [Authorize]
    public class CardController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ICardService _cardManager;
        private readonly ICardItemService _cardItemManager;
        private readonly IOrderService _orderManager;

        public CardController(UserManager<User> userManager, ICardService cardManager, ICardItemService cardItemManager, IOrderService orderManager)
        {
            _userManager = userManager;
            _cardManager = cardManager;
            _cardItemManager = cardItemManager;
            _orderManager = orderManager;
        }

        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            var card = await _cardManager.GetCardByUserId(userId);
            CardDto cardDto = new CardDto
            {
                CardId = card.Id,
                CardItems = card.CardItems.Select(ci => new CardItemDto
                {
                    CardItemId = ci.Id,
                    ProductId = ci.ProductId,
                    ProductName = ci.Product.Name,
                    ProductUrl = ci.Product.Url,
                    ItemPrice = ci.Product.Price,
                    ImageUrl = ci.Product.ImageUrl,
                    Quantity = ci.Quantity
                }).ToList()
            };
            return View(cardDto);
        }

        [HttpPost]
        public IActionResult AddToCard(int productId, int quantity)
        {
            var userId = _userManager.GetUserId(User);
            _cardManager.AddToCard(userId, productId, quantity);
            return RedirectToAction("Index", "Card");
        }
        [HttpPost]
        public async Task<IActionResult> ChangeQuantity(int cardItemId, int quantity)
        {
            await _cardItemManager.ChangeQuantity(cardItemId, quantity);
            return RedirectToAction("Index", "Card");
        }
        public async Task<IActionResult> DeleteFromCard(int id)
        {
            var cardItem = await _cardItemManager.GetByIdAsync(id);
            _cardItemManager.Delete(cardItem);
            return RedirectToAction("Index", "Card");
        }
        public async Task<IActionResult> Checkout()
        {
            var userId = _userManager.GetUserId(User);
            var user = await _userManager.FindByIdAsync(userId);
            var card = await _cardManager.GetCardByUserId(userId);
            OrderDto orderDto = new OrderDto
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Address = user.Address,
                City = user.City,
                Phone = user.PhoneNumber,
                Email = user.Email,
                CardDto = new CardDto
                {
                    CardId = card.Id,
                    CardItems = card.CardItems.Select(ci => new CardItemDto
                    {
                        CardItemId = ci.Id,
                        ProductId = ci.ProductId,
                        ProductName = ci.Product.Name,
                        ItemPrice = ci.Product.Price,
                        ImageUrl = ci.Product.ImageUrl,
                        ProductUrl = ci.Product.Url,
                        Quantity = ci.Quantity
                    }).ToList()
                }
            };
            return View(orderDto);
        }
        [HttpPost]
        public async Task<IActionResult> Checkout(OrderDto orderDto)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var card = await _cardManager.GetCardByUserId(userId);
                orderDto.CardDto = new CardDto
                {
                    CardId = card.Id,
                    CardItems = card.CardItems.Select(ci => new CardItemDto
                    {
                        CardItemId = ci.Id,
                        ProductId = ci.ProductId,
                        ProductName = ci.Product.Name,
                        ItemPrice = ci.Product.Price,
                        ImageUrl = ci.Product.ImageUrl,
                        ProductUrl = ci.Product.Url,
                        Quantity = ci.Quantity
                    }).ToList()
                };
                //Ödeme işlemleri ile ilgili kodları buraya yazacağız
                //1) Kredi kartı numarası kontrolü
                //2) Eğer kart numarası geçerliyse ödemeyi al
                //3) Ödeme başarılıysa Order'ı kaydet
                if (!CardNumberControl(orderDto.CardNumber))
                {
                    TempData["Message"] = Jobs.CreateMessage("Hata", "Kredi kartı numarası hatalıdır!", "danger");
                    return View(orderDto);
                }
                Payment payment = PaymentProcess(orderDto);
                if (payment.Status=="success")
                {
                    SaveOrder(orderDto, userId);
                    _cardItemManager.ClearCard(orderDto.CardDto.CardId);
                    TempData["Message"] = Jobs.CreateMessage("Başarılı", "Ödemeniz başarıyla alınmıştır.", "success");
                    return View("Success");
                }
                //
            }
            return RedirectToAction("Index", "Home");
        }
        [NonAction]
        private async void SaveOrder(OrderDto orderDto, string userId)
        {
            Order order = new Order();
            order.OrderNumber = "SA-" + new Random().Next(111111111, 999999999).ToString();
            order.OrderState = EnumOrderState.Unpaid;//Bunu geçici olarak yapıyoruz. Aslında buraya ödeme tamamlanmış halde geleceğiz ve buranın Completed olmasını sağlayacağız.
            order.OrderType = EnumOrderType.CreditCard;
            order.OrderDate = DateTime.Now;
            order.FirstName = orderDto.FirstName;
            order.LastName = orderDto.LastName;
            order.Email = orderDto.Email;
            order.Phone = orderDto.Phone;
            order.City = orderDto.City;
            order.Address = orderDto.Address;
            order.UserId = userId;
            order.OrderItems = new List<Entity.Concrete.OrderItem>();
            foreach (var item in orderDto.CardDto.CardItems)
            {
                var orderItem = new Entity.Concrete.OrderItem();
                orderItem.Price = item.ItemPrice;
                orderItem.Quantity = item.Quantity;
                orderItem.ProductId = item.ProductId;
                order.OrderItems.Add(orderItem);
            }
            await _orderManager.CreateAsync(order);
        }
        [NonAction]
        private bool CardNumberControl(string cardNumber)
        {
            #region Comment
            /*
             * - cardNumber boşluk karakterinden temizlensin
             * - cardNumber uzunluk kontrolü
             * - Sayısal değer kontrolü
             * - Luhn algoritmasınu uygulamak için gerekenleri yap
             */
            #endregion

            cardNumber = cardNumber.Replace("-", "").Replace(" ", "");
            if (cardNumber.Length != 16) return false;
            foreach (var chr in cardNumber)
            {
                if (!Char.IsNumber(chr)) return false;
            }
            int oddTotal = 0;
            int ovenTotal = 0;
            for (int i = 0; i < cardNumber.Length; i += 2)
            {
                int nextOddNumber = Convert.ToInt32(cardNumber[i].ToString());
                int nextOvenNumber = Convert.ToInt32(cardNumber[i + 1].ToString());

                int addedOddNumber = nextOddNumber * 2;
                addedOddNumber = addedOddNumber >= 10 ? addedOddNumber - 9 : addedOddNumber;

                oddTotal += addedOddNumber;
                ovenTotal += nextOvenNumber;
            }
            int total = oddTotal + ovenTotal;
            bool isValidNumber = total % 10 == 0 ? true : false;
            return isValidNumber;
        }
        [NonAction]
        private Payment PaymentProcess(OrderDto orderDto)
        {
            #region PaymentOptionsCreated
            Options options = new Options();
            options.ApiKey = "sandbox-WxQJB0q4pYxDbOpTzLGzPhBIHzNKdwcr";
            options.SecretKey = "sandbox-ojPweetnhhISE55zAM0vVNyvkkGvdMCv";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";
            #endregion

            #region CreatePaymentRequest
            CreatePaymentRequest request = new CreatePaymentRequest
            {
                Locale = Locale.TR.ToString(),
                ConversationId = new Random().Next(1111111, 9999999).ToString(),
                Price = Convert.ToInt32(orderDto.CardDto.TotalPrice()).ToString(),
                PaidPrice = Convert.ToInt32(orderDto.CardDto.TotalPrice()).ToString(),
                Currency = Currency.TRY.ToString(),
                Installment = 1,
                BasketId = orderDto.CardDto.CardId.ToString(),
                PaymentChannel = PaymentChannel.WEB.ToString(),
                PaymentGroup = PaymentGroup.PRODUCT.ToString(),
                PaymentCard = new PaymentCard
                {
                    CardHolderName = orderDto.CardName,
                    CardNumber = orderDto.CardNumber,
                    ExpireMonth = orderDto.ExpirationMonth,
                    ExpireYear = orderDto.ExpirationYear,
                    Cvc = orderDto.Cvc,
                    RegisterCard = 0
                },
                Buyer = new Buyer
                {
                    Id = "BY789",
                    Name = "Wissen",

Week_15/12-01-2023/ShoppingApp/ShoppingApp.Web/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using ShoppingApp.Business.Abstract;
using ShoppingApp.Business.Concrete;
using ShoppingApp.Entity.Concrete;
using ShoppingApp.Web.Models.Dtos;

namespace ShoppingApp.Web.Controllers
{
    public class ShopController : Controller
    {
        private readonly IProductService _productManager;

        public ShopController(IProductService productManager)
        {
            _productManager = productManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> ProductList(string categoryurl)
        {
            List<Product> products = await _productManager.GetProductsByCategoryAsync(categoryurl);
            List<ProductDto> productDtos = new List<ProductDto>();
            foreach (var product in products)
            {
                productDtos.Add(new ProductDto
                {
                    Id = product.Id,
                    Name = product.Name,
                    Price = product.Price,
                    ImageUrl = product.ImageUrl,
                    Url=product.Url,
                });
            }
            return View(productDtos);
        }
        public  async Task<IActionResult> ProductDetails(string producturl)
        {
            if (producturl==null)
            {
                return NotFound();
            }
            var product = await _productManager.GetProductDetailsByUrlAsync(producturl);
            ProductDetailsDto productDetailsDto = new ProductDetailsDto
            {
                Id = product.Id,
                Name = product.Name,
                Price = product.Price,
                ImageUrl = product.ImageUrl,
                Url = product.Url,
                Description = product.Description,
                Categories = product
                    .ProductCategories
                    .Select(pc => pc.Category)
                    .ToList()
            };

            return View(productDetailsDto);
        }
    }
}

Week_15/12-01-2023/ShoppingApp/ShoppingApp.Web/Views/Card/Checkout.cshtml
@model OrderDto
<h6 class="display-6">Ödeme</h6>
<div>@ViewBag.CardStatus</div>
<form asp-controller="Card"
      asp-action="Checkout"
      method="post"
    >
    <div class="row">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="col-8">
            <h6 class="display-6">Müşteri Bilgileri</h6>
            <div class="row mb-3">
                <div class="col-6">
                    <label class="form-label" asp-for="FirstName"></label>
                    <input class="form-control" asp-for="FirstName" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="col-6">
                    <label class="form-label" asp-for="LastName"></label>
                    <input class="form-control" asp-for="LastName" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-12">
                    <label class="form-label" asp-for="Address"></label>
                    <textarea class="form-control" asp-for="Address"></textarea>
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-4">
                    <label class="form-label" asp-for="City"></label>
                    <input class="form-control" asp-for="City" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="col-4">
                    <label class="form-label" asp-for="Phone"></label>
                    <input class="form-control" asp-for="Phone" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="col-4">
                    <label class="form-label" asp-for="Email"></label>
                    <input class="form-control" asp-for="Email" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <h6 class="display-6">Kart Bilgileri</h6>
            <div class="row mb-3">
                <div class="col-6">
                    <label class="form-label" asp-for="CardName"></label>
                    <input class="form-control" asp-for="CardName" />
                    <span asp-validation-for="CardName" class="text-danger"></span>
                </div>
                <div class="col-6">
                    <label class="form-label" asp-for="CardNumber"></label>
                    <input class="form-control" asp-for="CardNumber" />
                    <span asp-validation-for="CardNumber" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-3">
                    <label class="form-label" asp-for="ExpirationMonth"></label>
                    <input class="form-control" asp-for="ExpirationMonth" />
                    <span asp-validation-for="ExpirationMonth" class="text-danger"></span>
                </div>
                <div class="col-3">
                    <label class="form-label" asp-for="ExpirationYear"></label>
                    <input class="form-control" asp-for="ExpirationYear" />
                    <span asp-validation-for="ExpirationYear" class="text-danger"></span>
                </div>
                <div class="col-6">
                    <label class="form-label" asp-for="Cvc"></label>
                    <input class="form-control" asp-for="Cvc" />
                    <span asp-validation-for="Cvc" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="col-4">
            <h6 class="display-6">Satış Bilgileri</h6>
            <ul class="list-group mb-3">
                @foreach (var cardItem in Model.CardDto.CardItems)
                {
                    <li class="list-group-item">
                        <div><h6>@cardItem.ProductName</h6></div>
                        <span>Adet: @cardItem.Quantity</span>
                        <span>Fiyat: @($"{cardItem.ItemPrice:C0}")</span>
                        @{
                            decimal? total = cardItem.ItemPrice * cardItem.Quantity;
                        }
                        <span>Toplam: @($"{total:C0}")</span>
                    </li>
                }
                <li class="list-group-item">
                    <span>Toplam: </span>
                    <strong>@($"{Model.CardDto.TotalPrice():C0}")</strong>
                </li>
            </ul>
            <div class="text-end">
                <button class="btn btn-success">Ödemeyi Yap</button>
            </div>
            
        </div>
    </div>
</form>

Week_15/12-01-2023/ShoppingApp/ShoppingApp.Web/Views/Card/GetOrders.cshtml
@model List<OrderListDto>
<h6 class="display-6">Siparişlerim</h6>
<hr />
<table class="table table-bordered table-striped table-sm">
    <thead>
        <tr class="bg-danger text-white">
            <th>Sipariş No</th>
            <th>Tarih</th>
            <th>Sipariş Toplam</th>
            <th>Sipariş Detayı</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var order in Model)
        {
            <tr>
                <td>@order.OrderNumber</td>
                <td>@order.OrderDate.ToShortDateString()</td>
                <td>@($"{order.TotalPrice():C0}")</td>
                <td>
                    @await Html.PartialAsync("_OrderDetailPartial",order)
                </td>
            </tr>
        }

    </tbody>
</table>

Week_15/12-01-2023/ShoppingApp/ShoppingApp.Web/Views/Card/Index.cshtml
@model CardDto
<h6 class="display-6">Sepet</h6>
<hr />
@if (Model.CardItems.Count == 0)
{
    <div class="row">
        <div class="alert alert-warning">
            Sepetinizde ürün bulunmamaktadır.
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col-8">
            <h6 class="text-danger display-6">Ürünler</h6>
            <hr />
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th>Resim</th>
                        <th>Ürün</th>
                        <th>Fiyat</th>
                        <th>Adet</th>
                        <th>Toplam</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var cardItem in Model.CardItems)
                    {
                        <tr>
                            <td>
                                <a 
                                   asp-controller="Shop"
                                   asp-action="ProductDetails"
                                   asp-route-producturl=@cardItem.ProductUrl>
                                    <img src="~/images/@cardItem.ImageUrl" width="20" />
                                </a>
                            </td>
                            <td>
                                <a class="text-decoration-none"
                                   asp-controller="Shop"
                                   asp-action="ProductDetails"
                                   asp-route-producturl=@cardItem.ProductUrl>
                                    @cardItem.ProductName</a>
                            </td>
                            <td>@($"{cardItem.ItemPrice:C0}")</td>
                            <td>
                                <form id="form_@cardItem.ProductId"
                                      asp-controller="Card"
                                      asp-action="ChangeQuantity"
                                      method="post">
                                    <input type="hidden" name="cardItemId" value="@cardItem.CardItemId" />
                                      <input
                                          type="number"
                                          class="form-control d-inline-block"
                                          name="quantity"
                                          value="@cardItem.Quantity"
                                          min="1"
                                          max="10"
                                          style="width:75px;"
                                          onchange="document.getElementById('form_@cardItem.ProductId').submit();"
                                          />
                                </form>
                            </td>
                            @{
                                decimal? total = cardItem.ItemPrice * cardItem.Quantity;
                            }
                            <td>@($"{total:C0}")</td>
                            <td>
                                <a 
                                    asp-controller="Card"
                                    asp-action="DeleteFromCard"
                                    asp-route-id="@cardItem.CardItemId"
                                    class="btn btn-close btn-sm"></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-4">
            <h6 class="text-danger display-6">Özet Bilgiler</h6>
            <hr />
            <table class="table table-sm">
                <tbody>
                    <tr>
                        <th>Sepet Toplamı:</th>
                        <td>@($"{Model.TotalPrice():C0}")</td>
                    </tr>
                    <tr>
                        <th>Kargo:</th>
                        <td>Ücretsiz</td>
                    </tr>
                    <tr>
                        <th>Ödenecek Toplam Tutar:</th>
                        <td>@($"{Model.TotalPrice():C0}")</td>
                    </tr>
                </tbody>
            </table>
            <div>
                <a href="/" class="btn btn-success">Alışverişe Devam Et</a>
                <a 
                    asp-controller="Card"
                    asp-action="Checkout"
                    class="btn btn-primary">Ödeme Adımına Geç</a>
            </div>
        </div>
    </div>
}

Week_15/12-01-2023/ShoppingApp/ShoppingApp.Web/Views/Card/Success.cshtml
<h1 class="display-6">Ödeme İşlemi Sonucu</h1>